# ============================================
# Deployment
# ============================================
deployment:
  name: springboot-app           # deployment name
  replicas: 1
  image:
    repository: "" 
    tag: ""
    digest: ""
    pullPolicy: IfNotPresent

# ============================================
# Service
# ============================================
service:
  name: springboot-service
  type: LoadBalancer             # ClusterIP | NodePort | LoadBalancer
  port: 80
  targetPort: 8080
